spring:
  application:
    name: discovery-service-feign-client

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
    register-with-eureka: false
    fetch-registry: true

server:
  port: 7072